export const SET_CURRENT_USER = 'currentUser/SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'currentUser/LOGOUT_CURRENT_USER';

export const SET_PIZZA_TO_DEFAULT = 'pizza/SET_PIZZA_TO_DEFAULT';
export const ADD_PIZZA_TOPPING = 'pizza/ADD_PIZZA_TOPPING';
export const REMOVE_PIZZA_TOPPING = 'pizza/REMOVE_PIZZA_TOPPING';
export const SET_TOPPINGS_PRICE = 'pizza/SET_TOPPINGS_PRICE';
export const SET_PIZZA_SIZE_PRICE = 'pizza/SET_PIZZA_SIZE_PRICE';
export const SET_PIZZA_DISCOUNT_CODE = 'pizza/SET_PIZZA_DISCOUNT_CODE';
export const SET_PIZZA_DISCOUNT_CODE_USED =
  'pizza/SET_PIZZA_DISCOUNT_CODE_USED';
export const SET_PIZZA_QUANTITY = 'pizza/SET_PIZZA_QUANTITY';
